import React from "react";
import "../styles/globals.css";
import Menu from "@/components/Menu";
import { useRouter } from "next/router";
import MenuResponsive from "@/components/MenuResponsive";
import Head from "next/head";
import { createTheme, ThemeProvider } from "@mui/material/styles";
import ThemeCepra from "@/constants/theme";
import { Box } from "@mui/material";

const theme = createTheme({
  breakpoints: ThemeCepra.landing.breakpoints,
});

function MyApp({ Component, pageProps }) {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>O2I - Observatorio de la Organización y la Industria</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {router.pathname.includes("/administracion") ? (
        <div className="main-container">
          <div className="menu">
            <Menu />
          </div>
          <div className="main-admin">
            <Component {...pageProps} />
          </div>
        </div>
      ) : (
        <>
          <ThemeProvider theme={theme}>
            <div className="page">
              <Box className="header">
                <MenuResponsive />
              </Box>
              <Box className="content">
                <Component {...pageProps} />
              </Box>
            </div>
          </ThemeProvider>
        </>
      )}
    </>
  );
}

export default MyApp;
