import React from "react";
import "../styles/globals.css";
import Menu from "@/components/Menu";
import { useRouter } from "next/router";
import MenuResponsive from "@/components/MenuResponsive";
import Head from "next/head";
import Footer from "@/components/Footer";

function MyApp({ Component, pageProps }) {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Cepra</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {router.pathname.includes("/administracion") ? (
        <div className="main-container">
          <div className="menu">
            <Menu />
          </div>
          <div className="main-admin">
            <Component {...pageProps} />
          </div>
        </div>
      ) : (
        <>
          <div className="page">
              <div className="header">
                  <MenuResponsive />
              </div>
              <div className="content">
                  <Component {...pageProps} />
              </div>
          </div>
        </>
      )}
    </>
  );
}

export default MyApp;
