import React from "react";
import Head from "next/head";
import NProgress from "nprogress";
import "../styles/globals.css";
import { useRouter, Router } from "next/router";
import { createTheme, ThemeProvider } from "@mui/material/styles";
import { Box } from "@mui/material";

import { AuthProvider } from "@/lib/auth";
import ThemeCepra from "@/constants/theme";
import Menu from "@/components/Menu";
import MenuResponsive from "@/components/MenuResponsive";

const theme = createTheme({
  breakpoints: ThemeCepra.landing.breakpoints,
});

Router.events.on("routeChangeStart", (url) => {
  // console.log(`Loading: ${url}`);
  NProgress.start();
});
Router.events.on("routeChangeComplete", () => NProgress.done());
Router.events.on("routeChangeError", () => NProgress.done());

function MyApp({ Component, pageProps }) {
  const router = useRouter();

  return (
    <>
      <AuthProvider>
        <Head>
          <title>O2I - Observatorio de la Organización y la Industria</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/o2i/favicon.ico" />
        </Head>
        <Box className="header">
          <MenuResponsive />
        </Box>
        {router.pathname.includes("/administracion") ? (
          <div className="main-container">
            <div className="menu">
              <Menu />
            </div>
            <div className="main-admin">
              <Component {...pageProps} />
            </div>
          </div>
        ) : (
          <>
            <ThemeProvider theme={theme}>
              <div className="page">
                <Box className="content">
                  <Component {...pageProps} />
                </Box>
              </div>
            </ThemeProvider>
          </>
        )}
      </AuthProvider>
    </>
  );
}

export default MyApp;
